### ISSUE TITLE
Paper, B.2. Proof of Lemma 4.1 - Definition of ∆

### ISSUE THREAD

**Issue by ndvbd** [Jiacheng-Zhu-AIML/AsymmetryLoRA#1]
Hi Jiacheng, in the solution of B*, what is the definition of ∆? In section 4.1.1 I can see ∆=BA, but B is what we're trying to find, so how can B* contain B?

**Comment by Jiacheng-Zhu-AIML** [comment]
Hi ndvbd, thanks for raising this question! 
In section 4.1.1, specifically for Lemma 4.1 and 4.2, we define $\Delta = W_{tart} - W_0$ as the targeted change in weight matrix.

**Comment by ndvbd** [comment]
Can you show the last transition, how you moved from the argmin to the B* in B.2?

**Comment by ndvbd** [comment]
Okay, thanks

**Comment by Jiacheng-Zhu-AIML** [comment]
Thanks!
